services:
    servinow-sys:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                MYSQL_CLIENT: mysql-client
                POSTGRES_VERSION: 16
                PHP_EXTENSIONS: pdo_mysql # Adiciona a extensão PHP necessária para o MySQL
        image: sail-8.4/app
        ports:
            - '1234:80'
        environment:
            WWWUSER: sail
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '12345678'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: banco
            MYSQL_USER: sail
            MYSQL_PASSWORD: '12345678'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            command: "/bin/sh -c \" mysqld --skip-name-resolve=0 & sleep 10; mysql -u root -p12345678 -e \\\" CREATE USER IF NOT EXISTS 'sail'@'%' IDENTIFIED BY '12345678'; GRANT ALL PRIVILEGES ON banco.* TO 'sail'@'%'; FLUSH PRIVILEGES; \\\"; tail -f /dev/null \"\n"
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '12345678'
            retries: 3
            timeout: 5s
        # minio:
        #     image: 'minio:'
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local